### ISSUE TITLE
List of upcoming events

### ISSUE THREAD

**Issue by Kumayl00** [Kumayl00/project-planning-demo#1]
**User story**
'As a local resident, I want to see a list of upcoming community events so that I can find interesting events to attend.'

**Acceptance Criteria:**

- [ ] The testimonials page displays at least five client testimonials.
- [ ] Each testimonial includes the client's first name, year of wedding, and comments.
- [ ] The testimonials section is responsive and looks good on multiple device sizes.

**Tasks:**

- [ ] Create an HTML section for testimonials.
- [ ] Style the testimonials section using CSS and Bootstrap.
- [ ] Use Bootstrap's grid system to make sure the testimonials section is responsive.
